User.create(username: 'admin', email: 'admin@test.com', password: 'password')
User.create(username: 'satou', email: 'satou@test.com', password: 'password')
User.create(username: 'suzuki', email: 'suzuki@test.com', password: 'password')
User.create(username: 'tanaka', email: 'tanaka@test.com', password: 'password')
User.create(username: 'test', email: 'test@test.com', password: 'password')
